# How many distinct terms are in the sequence generated by ab for 2  a  100 and 2  b  100?

l = []
i = 0
for q in range(2,101):
	for w in range(2,101):
		try:
			l.index(q**w)
		except:
			l.append(q**w)
a = len(l)
print a

# ==> 9183