# The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
# 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
# Let us list the factors of the first seven triangle numbers:

#  1: 1
#  3: 1,3
#  6: 1,2,3,6
# 10: 1,2,5,10
# 15: 1,3,5,15
# 21: 1,3,7,21
# 28: 1,2,4,7,14,28
# We can see that 28 is the first triangle number to have over five divisors.

# What is the value of the first triangle number to have over five hundred divisors?
from math import *
def div(number):
        i=1
        divisible = [1, number, int(ceil(sqrt(number)))]
        for j in range(2, int(ceil(sqrt(number)))):
        	while i<j:
        		if j % i == 0:
        			divisible.append(i)
        		i+=1
    	return len(divisible)
i=1
a=0
while True:
	j = i
	n = 0
	while j>0:
		n += j
		j-=1
	if div(n)>=500:
		a = n
		break
	i+=1
print a